export class BackgroundData {
    public a: string;
    public b: string;
    public c: string;
    public d: string;
    public e: string;
    public f: string;
    public g: string;
    public h: string;
    public i: string;
    public j: string;
    public k: string;
    public l: string;
    public m: string;
    public n: string;
    public o: string;
    public p: string;
    public q: string;
    public r: string;
    public s: string;
    public t: string;
    public u: string;
    public v: string;
    public w: string;
    public x: string;
    public y: string;
    public z: string;

    constructor(...colors: string[]) {
        this.a = colors[0];
        this.b = colors[1];
        this.c = colors[2];
        this.d = colors[3];
        this.e = colors[4];
        this.f = colors[5];
        this.g = colors[6];
        this.h = colors[7];
        this.i = colors[8];
        this.j = colors[9];
        this.k = colors[10];
        this.l = colors[11];
        this.m = colors[12];
        this.n = colors[13];
        this.o = colors[14];
        this.p = colors[15];
        this.q = colors[16];
        this.r = colors[17];
        this.s = colors[18];
        this.t = colors[19];
        this.u = colors[20];
        this.v = colors[21];
        this.w = colors[22];
        this.x = colors[23];
        this.y = colors[24];
        this.z = colors[25];
    }
}